<?php
/**
 * Certificate PDF template.
 *
 * Expected variables: $order, $certificate_number, $package_label,
 * $book_quantity, $donor_name, $certificate_date, $program_name.
 *
 * @package YIARI_Campaign_Toolkit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<style>
		body {
			font-family: DejaVu Sans, sans-serif;
			color: #1e293b;
			margin: 0;
			padding: 0;
		}
		.certificate {
			border: 10px solid #256f5b;
			padding: 42px 56px;
			height: 660px;
			box-sizing: border-box;
		}
		.brand {
			font-size: 34px;
			font-weight: 700;
			color: #256f5b;
			letter-spacing: 2px;
			text-align: center;
			margin-bottom: 26px;
		}
		.eyebrow {
			font-size: 13px;
			text-transform: uppercase;
			text-align: center;
			color: #64748b;
			margin-bottom: 12px;
		}
		h1 {
			font-size: 42px;
			text-align: center;
			margin: 0 0 28px;
			color: #0f513f;
		}
		.name {
			font-size: 34px;
			font-weight: 700;
			text-align: center;
			margin: 18px 0;
		}
		.copy {
			font-size: 18px;
			line-height: 1.55;
			text-align: center;
			max-width: 760px;
			margin: 0 auto 32px;
		}
		.meta {
			width: 100%;
			border-collapse: collapse;
			margin-top: 30px;
			font-size: 14px;
		}
		.meta td {
			padding: 9px 12px;
			border-top: 1px solid #cbd5e1;
		}
		.meta strong {
			color: #0f513f;
		}
		.footer {
			margin-top: 34px;
			font-size: 12px;
			text-align: center;
			color: #64748b;
		}
	</style>
</head>
<body>
	<div class="certificate">
		<div class="brand">YIARI</div>
		<div class="eyebrow"><?php echo esc_html( $program_name ); ?></div>
		<h1><?php esc_html_e( 'Certificate of Appreciation', 'yiari-campaign-toolkit' ); ?></h1>
		<p class="copy"><?php esc_html_e( 'This certificate is presented to', 'yiari-campaign-toolkit' ); ?></p>
		<div class="name"><?php echo esc_html( $donor_name ); ?></div>
		<p class="copy">
			<?php
			printf(
				/* translators: 1: package label, 2: book quantity. */
				esc_html__( 'for supporting %1$s with %2$d campaign package(s), helping conservation education reach more readers.', 'yiari-campaign-toolkit' ),
				esc_html( $package_label ),
				absint( $book_quantity )
			);
			?>
		</p>
		<table class="meta">
			<tr>
				<td><strong><?php esc_html_e( 'Certificate No.', 'yiari-campaign-toolkit' ); ?></strong><br><?php echo esc_html( $certificate_number ); ?></td>
				<td><strong><?php esc_html_e( 'Order No.', 'yiari-campaign-toolkit' ); ?></strong><br>#<?php echo esc_html( $order->get_order_number() ); ?></td>
				<td><strong><?php esc_html_e( 'Date', 'yiari-campaign-toolkit' ); ?></strong><br><?php echo esc_html( $certificate_date ); ?></td>
			</tr>
		</table>
		<div class="footer"><?php esc_html_e( 'Generated by YIARI Campaign Toolkit.', 'yiari-campaign-toolkit' ); ?></div>
	</div>
</body>
</html>
